# Generated by Django 5.1.14 on 2026-07-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coachcomment",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="coach_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="training_plans", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="created_plans", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="weeklyplan",
            name="training_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="weeks", to="training.trainingplan"
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="weekly_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workouts", to="training.weeklyplan"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="exercises", to="training.workout"
            ),
        ),
        migrations.AddField(
            model_name="coachcomment",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="coach_comments", to="training.workout"
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workout_logs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="workout",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="log", to="training.workout"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyplan",
            constraint=models.UniqueConstraint(fields=("training_plan", "week_number"), name="unique_plan_week"),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(fields=("workout", "order"), name="unique_workout_exercise_order"),
        ),
    ]
