# Generated by Django 5.1.14 on 2026-07-17 07:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="recovery_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_max",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("heart_rate", "Heart rate"),
                    ("pace", "Pace"),
                    ("power", "Power"),
                    ("rpe", "Perceived exertion"),
                ],
                default="free",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_unit",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="TrainingZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("triathlon", "Triathlon"),
                            ("swimming", "Swimming"),
                            ("cycling", "Cycling"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("heart_rate", "Heart rate"), ("pace", "Pace"), ("power", "Power")], max_length=16
                    ),
                ),
                (
                    "zone_number",
                    models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("name", models.CharField(max_length=100)),
                ("lower_bound", models.DecimalField(decimal_places=2, max_digits=8)),
                ("upper_bound", models.DecimalField(decimal_places=2, max_digits=8)),
                ("unit", models.CharField(max_length=20)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("sport", "metric", "zone_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("athlete", "sport", "metric", "zone_number"), name="unique_athlete_training_zone"
                    )
                ],
            },
        ),
    ]
