# Generated by Django 5.2.16 on 2026-07-18 11:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0007_plan_phases_and_workout_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(choices=[("file_upload", "File upload")], default="file_upload", max_length=20),
                ),
                ("source_file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(choices=[("fit", "FIT"), ("tcx", "TCX"), ("gpx", "GPX")], max_length=8)),
                ("file_sha256", models.CharField(max_length=64)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("triathlon", "Triathlon"),
                            ("swimming", "Swimming"),
                            ("cycling", "Cycling"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("moving_time_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("distance_meters", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("elevation_gain_meters", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("average_heart_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maximum_heart_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("average_power", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maximum_power", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("normalized_power", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("average_cadence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maximum_cadence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("average_speed_mps", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("average_pace_seconds_per_km", models.PositiveIntegerField(blank=True, null=True)),
                ("intensity_factor", models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ("training_load_score", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("training_load_method", models.CharField(blank=True, max_length=32)),
                (
                    "compliance_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("on_target", "On target"),
                            ("under", "Below target"),
                            ("over", "Above target"),
                            ("unplanned", "Unplanned"),
                            ("insufficient_data", "Insufficient data"),
                        ],
                        default="unplanned",
                        max_length=24,
                    ),
                ),
                (
                    "match_confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("manual", "Manual"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("zone_distribution", models.JSONField(blank=True, default=dict)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="training.workout",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ActivityStream",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points", models.JSONField(default=list)),
                ("point_count", models.PositiveIntegerField(default=0)),
                ("sample_interval_seconds", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stream", to="training.activity"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["athlete", "started_at"], name="activity_athlete_start_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["workout", "started_at"], name="activity_workout_start_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["sport", "started_at"], name="activity_sport_start_idx"),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(fields=("athlete", "file_sha256"), name="unique_athlete_activity_file"),
        ),
    ]
