# Generated by Django 5.2.16 on 2026-07-28 15:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0011_training_plan_generation_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellnessCheckIn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_in_date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "sleep_duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "sleep_quality",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "fatigue",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "stress",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "muscle_soreness",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "overall_feeling",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "resting_heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(220),
                        ],
                    ),
                ),
                (
                    "hrv_rmssd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "illness_severity",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Mild"), (2, "Moderate"), (3, "Severe")], default=0
                    ),
                ),
                (
                    "injury_severity",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Mild"), (2, "Moderate"), (3, "Severe")], default=0
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("share_with_coach", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("device", "Device")], default="manual", max_length=16
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-check_in_date", "-created_at"),
                "indexes": [models.Index(fields=["athlete", "check_in_date"], name="wellness_athlete_date_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("athlete", "check_in_date"), name="unique_athlete_wellness_date")
                ],
            },
        ),
    ]
