import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def seed_system_templates(apps, schema_editor):
    WorkoutTemplate = apps.get_model("training", "WorkoutTemplate")

    def step(
        name,
        name_ru,
        step_type,
        *,
        duration=None,
        distance=None,
        target_type="free",
        zone=None,
        repetitions=1,
        recovery=None,
        description="",
        description_ru="",
    ):
        return {
            "name": name,
            "name_ru": name_ru,
            "step_type": step_type,
            "description": description,
            "description_ru": description_ru,
            "repetitions": repetitions,
            "duration_seconds": duration,
            "distance_meters": distance,
            "recovery_seconds": recovery,
            "target_type": target_type,
            "target_min": zone,
            "target_max": zone,
            "target_unit": "zone" if zone else "",
        }

    templates = [
        {
            "slug": "run-recovery-40",
            "title": "Recovery run · 40 min",
            "title_ru": "Восстановительный бег · 40 мин",
            "sport": "running",
            "workout_type": "recovery",
            "description": "Low-load aerobic movement for recovery between demanding sessions.",
            "description_ru": "Лёгкая аэробная работа для восстановления между тяжёлыми тренировками.",
            "objective": "Restore movement quality without adding meaningful fatigue.",
            "objective_ru": "Восстановить качество движения без существенного накопления усталости.",
            "difficulty": "all",
            "tags": ["recovery", "aerobic"],
            "equipment": ["running_shoes"],
            "planned_duration_minutes": 40,
            "intensity": "Z1",
            "structured_steps": [
                step("Easy warm-up", "Лёгкая разминка", "warmup", duration=600, target_type="heart_rate", zone=1),
                step(
                    "Relaxed aerobic running",
                    "Спокойный аэробный бег",
                    "steady",
                    duration=1500,
                    target_type="heart_rate",
                    zone=1,
                ),
                step("Cool-down", "Заминка", "cooldown", duration=300, target_type="heart_rate", zone=1),
            ],
        },
        {
            "slug": "run-endurance-60",
            "title": "Aerobic endurance · 60 min",
            "title_ru": "Аэробная выносливость · 60 мин",
            "sport": "running",
            "workout_type": "endurance",
            "description": "Foundational continuous running with stable aerobic intensity.",
            "description_ru": "Базовый непрерывный бег со стабильной аэробной интенсивностью.",
            "objective": "Develop aerobic durability and efficient pacing.",
            "objective_ru": "Развивать аэробную устойчивость и экономичное поддержание темпа.",
            "difficulty": "all",
            "tags": ["base", "aerobic"],
            "equipment": ["running_shoes"],
            "planned_duration_minutes": 60,
            "intensity": "Z2",
            "structured_steps": [
                step(
                    "Progressive warm-up",
                    "Постепенная разминка",
                    "warmup",
                    duration=600,
                    target_type="heart_rate",
                    zone=1,
                ),
                step("Aerobic endurance", "Аэробная работа", "steady", duration=2400, target_type="heart_rate", zone=2),
                step("Cool-down", "Заминка", "cooldown", duration=600, target_type="heart_rate", zone=1),
            ],
        },
        {
            "slug": "run-threshold-4x8",
            "title": "Threshold development · 4 × 8 min",
            "title_ru": "Развитие порога · 4 × 8 мин",
            "sport": "running",
            "workout_type": "threshold",
            "description": "Controlled threshold intervals with short aerobic recoveries.",
            "description_ru": "Контролируемые пороговые интервалы с коротким аэробным восстановлением.",
            "objective": "Accumulate sustainable work near lactate threshold.",
            "objective_ru": "Накопить устойчивую работу вблизи лактатного порога.",
            "difficulty": "intermediate",
            "tags": ["threshold", "intervals"],
            "equipment": ["running_shoes", "heart_rate_monitor"],
            "planned_duration_minutes": 66,
            "intensity": "Z4",
            "structured_steps": [
                step("Warm-up", "Разминка", "warmup", duration=900, target_type="pace", zone=2),
                step(
                    "Threshold intervals",
                    "Пороговые интервалы",
                    "work",
                    duration=480,
                    target_type="pace",
                    zone=4,
                    repetitions=4,
                    recovery=120,
                ),
                step("Cool-down", "Заминка", "cooldown", duration=900, target_type="pace", zone=1),
            ],
        },
        {
            "slug": "run-vo2-6x3",
            "title": "VO₂max · 6 × 3 min",
            "title_ru": "VO₂max · 6 × 3 мин",
            "sport": "running",
            "workout_type": "vo2_max",
            "description": "High-quality aerobic-power intervals with equal active recovery.",
            "description_ru": "Качественные интервалы аэробной мощности с равным активным восстановлением.",
            "objective": "Improve maximal aerobic power while preserving repeat quality.",
            "objective_ru": "Повысить максимальную аэробную мощность, сохраняя качество повторов.",
            "difficulty": "advanced",
            "tags": ["vo2max", "intervals"],
            "equipment": ["running_shoes", "heart_rate_monitor"],
            "planned_duration_minutes": 58,
            "intensity": "Z5",
            "structured_steps": [
                step(
                    "Warm-up and strides", "Разминка и ускорения", "warmup", duration=1200, target_type="pace", zone=2
                ),
                step(
                    "VO₂max intervals",
                    "Интервалы VO₂max",
                    "work",
                    duration=180,
                    target_type="pace",
                    zone=5,
                    repetitions=6,
                    recovery=180,
                ),
                step("Cool-down", "Заминка", "cooldown", duration=900, target_type="pace", zone=1),
            ],
        },
        {
            "slug": "run-long-progression-100",
            "title": "Progressive long run · 100 min",
            "title_ru": "Прогрессивный длительный бег · 100 мин",
            "sport": "running",
            "workout_type": "long",
            "description": "Long aerobic run finishing with controlled steady work.",
            "description_ru": "Длительный аэробный бег с контролируемым ускорением в заключительной части.",
            "objective": "Build durability and finish efficiently under accumulated fatigue.",
            "objective_ru": "Развивать выносливость и экономично завершать работу на фоне усталости.",
            "difficulty": "intermediate",
            "tags": ["long", "progression"],
            "equipment": ["running_shoes", "hydration"],
            "planned_duration_minutes": 100,
            "intensity": "Z2–Z3",
            "structured_steps": [
                step("Easy opening", "Спокойное начало", "warmup", duration=900, target_type="heart_rate", zone=1),
                step(
                    "Aerobic endurance",
                    "Аэробная выносливость",
                    "steady",
                    duration=3900,
                    target_type="heart_rate",
                    zone=2,
                ),
                step("Steady finish", "Устойчивое завершение", "work", duration=900, target_type="heart_rate", zone=3),
                step("Cool-down", "Заминка", "cooldown", duration=300, target_type="heart_rate", zone=1),
            ],
        },
        {
            "slug": "bike-endurance-90",
            "title": "Endurance ride · 90 min",
            "title_ru": "Тренировка выносливости · 90 мин",
            "sport": "cycling",
            "workout_type": "endurance",
            "description": "Stable endurance ride guided by power or heart rate.",
            "description_ru": "Стабильная тренировка выносливости под контролем мощности или пульса.",
            "objective": "Build aerobic capacity and pedalling consistency.",
            "objective_ru": "Развивать аэробную мощность и стабильность педалирования.",
            "difficulty": "all",
            "tags": ["base", "endurance"],
            "equipment": ["bike", "power_meter"],
            "planned_duration_minutes": 90,
            "intensity": "Power Z2",
            "structured_steps": [
                step(
                    "Progressive warm-up", "Постепенная разминка", "warmup", duration=900, target_type="power", zone=1
                ),
                step(
                    "Endurance riding", "Работа на выносливость", "steady", duration=3900, target_type="power", zone=2
                ),
                step("Cool-down", "Заминка", "cooldown", duration=600, target_type="power", zone=1),
            ],
        },
        {
            "slug": "bike-sweet-spot-3x12",
            "title": "Sweet spot · 3 × 12 min",
            "title_ru": "Sweet spot · 3 × 12 мин",
            "sport": "cycling",
            "workout_type": "tempo",
            "description": "Sustained sub-threshold work with controlled recovery.",
            "description_ru": "Продолжительная работа ниже порога с контролируемым восстановлением.",
            "objective": "Increase sustainable power with manageable fatigue cost.",
            "objective_ru": "Повысить устойчивую мощность при контролируемой цене усталости.",
            "difficulty": "intermediate",
            "tags": ["sweet_spot", "power"],
            "equipment": ["bike", "power_meter"],
            "planned_duration_minutes": 75,
            "intensity": "Power Z3–Z4",
            "structured_steps": [
                step("Warm-up", "Разминка", "warmup", duration=900, target_type="power", zone=2),
                step(
                    "Sweet spot intervals",
                    "Интервалы sweet spot",
                    "work",
                    duration=720,
                    target_type="power",
                    zone=4,
                    repetitions=3,
                    recovery=300,
                ),
                step("Cool-down", "Заминка", "cooldown", duration=600, target_type="power", zone=1),
            ],
        },
        {
            "slug": "bike-vo2-5x4",
            "title": "Cycling VO₂max · 5 × 4 min",
            "title_ru": "Велосипедный VO₂max · 5 × 4 мин",
            "sport": "cycling",
            "workout_type": "vo2_max",
            "description": "Repeatable high-power intervals with full aerobic recoveries.",
            "description_ru": "Повторяемые интервалы высокой мощности с полноценным аэробным восстановлением.",
            "objective": "Improve aerobic power and repeatability above threshold.",
            "objective_ru": "Развивать аэробную мощность и повторяемость усилий выше порога.",
            "difficulty": "advanced",
            "tags": ["vo2max", "power"],
            "equipment": ["bike", "power_meter"],
            "planned_duration_minutes": 65,
            "intensity": "Power Z5",
            "structured_steps": [
                step("Warm-up", "Разминка", "warmup", duration=1200, target_type="power", zone=2),
                step(
                    "VO₂max intervals",
                    "Интервалы VO₂max",
                    "work",
                    duration=240,
                    target_type="power",
                    zone=5,
                    repetitions=5,
                    recovery=240,
                ),
                step("Cool-down", "Заминка", "cooldown", duration=900, target_type="power", zone=1),
            ],
        },
        {
            "slug": "swim-technique-1800",
            "title": "Technique and efficiency · 1800 m",
            "title_ru": "Техника и эффективность · 1800 м",
            "sport": "swimming",
            "workout_type": "technique",
            "description": "Technique-focused pool session with short aerobic repeats.",
            "description_ru": "Техническая тренировка в бассейне с короткими аэробными повторами.",
            "objective": "Improve stroke quality before adding intensity.",
            "objective_ru": "Улучшить качество гребка перед повышением интенсивности.",
            "difficulty": "all",
            "tags": ["technique", "pool"],
            "equipment": ["pool", "pull_buoy"],
            "planned_distance_km": "1.80",
            "intensity": "Easy–moderate",
            "structured_steps": [
                step("Easy swim", "Лёгкое плавание", "warmup", distance=400),
                step("Technique drills", "Технические упражнения", "drill", distance=50, repetitions=8, recovery=20),
                step(
                    "Aerobic repeats",
                    "Аэробные повторы",
                    "work",
                    distance=200,
                    target_type="pace",
                    zone=3,
                    repetitions=4,
                    recovery=30,
                ),
                step("Easy cool-down", "Лёгкая заминка", "cooldown", distance=200),
            ],
        },
        {
            "slug": "swim-css-10x100",
            "title": "CSS threshold · 10 × 100 m",
            "title_ru": "Порог CSS · 10 × 100 м",
            "sport": "swimming",
            "workout_type": "threshold",
            "description": "Pool threshold set anchored to the athlete's critical swim speed.",
            "description_ru": "Пороговая серия в бассейне относительно критической скорости плавания спортсмена.",
            "objective": "Accumulate controlled swimming near critical speed.",
            "objective_ru": "Накопить контролируемую работу вблизи критической скорости плавания.",
            "difficulty": "intermediate",
            "tags": ["css", "threshold", "pool"],
            "equipment": ["pool", "pace_clock"],
            "planned_distance_km": "2.00",
            "intensity": "Pace Z4",
            "structured_steps": [
                step("Warm-up", "Разминка", "warmup", distance=600),
                step(
                    "CSS intervals",
                    "Интервалы CSS",
                    "work",
                    distance=100,
                    target_type="pace",
                    zone=4,
                    repetitions=10,
                    recovery=20,
                ),
                step("Cool-down", "Заминка", "cooldown", distance=400),
            ],
        },
        {
            "slug": "tri-brick-aerobic",
            "title": "Aerobic brick · bike to run",
            "title_ru": "Аэробная связка · велосипед + бег",
            "sport": "triathlon",
            "workout_type": "brick",
            "description": "Controlled bike-to-run transition session guided by heart rate.",
            "description_ru": "Контролируемая связка велосипед–бег под контролем пульса.",
            "objective": "Develop transition efficiency without excessive intensity.",
            "objective_ru": "Развивать эффективность перехода без избыточной интенсивности.",
            "difficulty": "intermediate",
            "tags": ["brick", "transition"],
            "equipment": ["bike", "running_shoes"],
            "planned_duration_minutes": 85,
            "intensity": "HR Z2–Z3",
            "structured_steps": [
                step(
                    "Bike endurance",
                    "Велосипедная выносливость",
                    "steady",
                    duration=3600,
                    target_type="heart_rate",
                    zone=2,
                ),
                step("Transition", "Транзитная зона", "recovery", duration=300),
                step("Progressive run", "Прогрессивный бег", "work", duration=1200, target_type="heart_rate", zone=3),
            ],
        },
    ]

    for template in templates:
        WorkoutTemplate.objects.update_or_create(
            slug=template["slug"],
            defaults={**template, "coach": None, "is_system": True, "schema_version": 1},
        )


def remove_system_templates(apps, schema_editor):
    WorkoutTemplate = apps.get_model("training", "WorkoutTemplate")
    WorkoutTemplate.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0012_wellnesscheckin"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workouts",
                to="training.workouttemplate",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="structure_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("heart_rate", "Heart rate"),
                    ("pace", "Pace"),
                    ("power", "Power"),
                    ("cadence", "Cadence"),
                    ("rpe", "Perceived exertion"),
                ],
                default="free",
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="workouttemplate",
            name="unique_coach_sport_template_title",
        ),
        migrations.AlterField(
            model_name="workouttemplate",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(model_name="workouttemplate", name="description_ru", field=models.TextField(blank=True)),
        migrations.AddField(
            model_name="workouttemplate",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("all", "All levels"),
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="all",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="equipment",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="is_system",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="objective",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="objective_ru",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="schema_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="title_ru",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="workouttemplate",
            constraint=models.UniqueConstraint(
                condition=Q(coach__isnull=False),
                fields=("coach", "sport", "title"),
                name="unique_coach_sport_template_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="workouttemplate",
            constraint=models.CheckConstraint(
                condition=(
                    Q(coach__isnull=True, is_system=True, slug__isnull=False) | Q(coach__isnull=False, is_system=False)
                ),
                name="template_system_ownership_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="workouttemplate",
            index=models.Index(
                fields=["is_system", "sport", "workout_type"],
                name="template_system_sport_type_idx",
            ),
        ),
    ]
