import { FormEvent, useEffect, useState } from "react";
import { Link, Navigate, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { api } from "./api";
import { useAuth } from "./auth";
import type { Analytics, Relationship, TrainingPlan, Workout } from "./types";

function AuthPage() {
  const { login, user } = useAuth(); const navigate = useNavigate();
  const [mode, setMode] = useState<"login" | "register">("login"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [submitting, setSubmitting] = useState(false);
  if (user) return <Navigate to="/" replace />;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (submitting) return;
    setSubmitting(true); setError(""); setNotice(""); const data = Object.fromEntries(new FormData(event.currentTarget));
    try { if (mode === "login") { await login(String(data.username), String(data.password)); navigate("/"); } else { await api.register(data as Record<string,string>); setNotice("Account created. Open the verification email before signing in."); setMode("login"); } } catch (e) { setError((e as Error).message || "The request could not be completed."); } finally { setSubmitting(false); }
  }
  return <main className="auth-shell"><section className="auth-story"><span className="eyebrow">ENDURANCE / TRAINING</span><h1>Build consistency.<br/><em>Measure progress.</em></h1><p>One calm workspace for coaches and endurance athletes.</p><div className="metric-row"><span>Plan</span><i></i><span>Execute</span><i></i><span>Adapt</span></div></section><section className="auth-card"><div className="brand-mark">EA</div><h2>{mode === "login" ? "Welcome back" : "Create your account"}</h2><p>{mode === "login" ? "Sign in to continue your training cycle." : "Start with the role that matches your work."}</p>{notice && <div className="notice" role="status">{notice}</div>}{error && <div className="error" role="alert">{error}</div>}<form onSubmit={submit}>{mode === "register" && <><label>Email<input name="email" type="email" required /></label><div className="two"><label>First name<input name="first_name" /></label><label>Last name<input name="last_name" /></label></div></>}<label>Username<input name="username" autoComplete="username" required /></label><label>Password<input name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} required /></label>{mode === "register" && <label>Role<select name="role"><option value="athlete">Athlete</option><option value="coach">Coach</option></select></label>}<button className="primary" disabled={submitting}>{submitting ? (mode === "login" ? "Signing in..." : "Creating account...") : (mode === "login" ? "Sign in" : "Create account")}</button></form>{mode === "login" && <Link className="text-button" to="/account-help">Verify email or reset password</Link>}<button className="text-button" disabled={submitting} onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); setNotice(""); }}>{mode === "login" ? "New here? Create an account" : "Already registered? Sign in"}</button></section></main>;
}

function SimpleAuthCard({ title, text, children }: { title: string; text: string; children?: React.ReactNode }) { return <main className="auth-shell"><section className="auth-story"><span className="eyebrow">ACCOUNT SECURITY</span><h1>Secure access.<br/><em>Clear progress.</em></h1></section><section className="auth-card"><div className="brand-mark">EA</div><h2>{title}</h2><p>{text}</p>{children}<Link className="text-button" to="/auth">Back to sign in</Link></section></main>; }

function VerifyEmailPage() { const [params]=useSearchParams(); const [message,setMessage]=useState("Verifying your email…"); useEffect(()=>{const token=params.get("token"); if(!token){setMessage("The verification link is incomplete.");return;} api.verifyEmail(token).then(()=>setMessage("Email verified. You can now sign in.")).catch(e=>setMessage(e.message));},[params]); return <SimpleAuthCard title="Email verification" text={message}/>; }

function AccountHelpPage() { const [message,setMessage]=useState(""); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{if(data.action==="verify")await api.requestVerification(String(data.email));else await api.requestPasswordReset(String(data.email));setMessage("If the account matches, an email has been sent.");}catch(err){setMessage((err as Error).message)}} return <SimpleAuthCard title="Account help" text="Request a new verification email or reset your password.">{message&&<div className="notice">{message}</div>}<form onSubmit={submit}><label>Email<input name="email" type="email" required/></label><label>Action<select name="action"><option value="verify">Verify email</option><option value="reset">Reset password</option></select></label><button className="primary">Send email</button></form></SimpleAuthCard>; }

function ResetPasswordPage() { const [params]=useSearchParams(); const [message,setMessage]=useState(""); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const password=String(new FormData(e.currentTarget).get("password"));try{await api.confirmPasswordReset(params.get("uid")||"",params.get("token")||"",password);setMessage("Password updated. You can now sign in.");}catch(err){setMessage((err as Error).message)}} return <SimpleAuthCard title="Choose a new password" text="Use a strong, unique password.">{message&&<div className="notice">{message}</div>}<form onSubmit={submit}><label>New password<input name="password" type="password" minLength={8} required/></label><button className="primary">Update password</button></form></SimpleAuthCard>; }

function InvitationPage() { const {token}=useParams(); const {user}=useAuth(); const [message,setMessage]=useState("Accepting invitation…"); useEffect(()=>{if(!user){setMessage("Sign in as the invited athlete, then open this link again.");return;} if(token)api.acceptInvitation(token).then(()=>setMessage("Invitation accepted. Your coach is now connected.")).catch(e=>setMessage(e.message));},[token,user]); return <SimpleAuthCard title="Coach invitation" text={message}/>; }

function Layout({ children }: { children: React.ReactNode }) { const { user, logout } = useAuth(); return <div className="app-shell"><aside><div className="logo">EA</div><div><strong>Endurance</strong><small>Training platform</small></div><nav><NavLink to="/">Overview</NavLink><NavLink to="/plans">Training plans</NavLink>{user?.role === "coach" && <NavLink to="/athletes">Athletes</NavLink>}</nav><div className="account"><span>{user?.first_name?.[0] || user?.username[0]}</span><div><strong>{user?.first_name || user?.username}</strong><small>{user?.role}</small></div><button onClick={logout} aria-label="Sign out">↗</button></div></aside><div className="content"><header><div><span className="eyebrow">{user?.role} workspace</span><h1>Good training starts with clarity.</h1></div><div className="live"><i></i> API connected</div></header>{children}</div></div>; }

function Protected({ children }: { children: React.ReactNode }) { const { user, loading } = useAuth(); if (loading) return <div className="loader">Loading training data…</div>; if (!user) return <Navigate to="/auth" replace />; return <Layout>{children}</Layout>; }

function Overview() { const { user } = useAuth(); const [plans,setPlans]=useState<TrainingPlan[]>([]); const [stats,setStats]=useState<Analytics|null>(null); useEffect(()=>{api.plans().then(x=>setPlans(x.results)); if(user?.role==="coach") api.analytics().then(setStats);},[user]); const workouts=plans.flatMap(p=>p.weeks.flatMap(w=>w.workouts)); const next=workouts.filter(w=>new Date(w.scheduled_at)>=new Date()).sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at)).slice(0,4); return <><section className="hero-panel"><div><span className="eyebrow">CURRENT CYCLE</span><h2>{plans[0]?.title ?? "Your training cycle is ready"}</h2><p>{plans[0]?.description || "Create a plan and turn long-term goals into consistent daily work."}</p></div><div className="ring"><strong>{stats?.completion_rate ?? workouts.filter(w=>w.status==="completed").length}</strong><small>{stats ? "% complete" : "completed"}</small></div></section><section className="stat-grid"><Stat label="Active plans" value={plans.filter(p=>p.is_active).length}/><Stat label="Planned sessions" value={stats?.total_workouts ?? workouts.length}/><Stat label="Distance completed" value={`${stats?.actual_distance_km ?? "0.00"} km`}/><Stat label="Average effort" value={stats?.average_perceived_exertion ?? "—"}/></section><div className="section-title"><div><span className="eyebrow">COMING UP</span><h2>Next sessions</h2></div><NavLink to="/plans">View all →</NavLink></div><section className="session-list">{next.length ? next.map(w=><WorkoutRow key={w.id} workout={w}/>) : <Empty text="No upcoming sessions yet."/>}</section></>; }
function Stat({label,value}:{label:string;value:string|number}) { return <article className="stat"><small>{label}</small><strong>{value}</strong></article>; }
function WorkoutRow({workout}:{workout:Workout}) { return <article className="workout-row"><time><strong>{new Date(workout.scheduled_at).toLocaleDateString("en",{day:"2-digit"})}</strong><small>{new Date(workout.scheduled_at).toLocaleDateString("en",{month:"short"})}</small></time><div className={`sport ${workout.sport}`}></div><div className="grow"><strong>{workout.title}</strong><small>{workout.sport} · {workout.intensity || "Open intensity"}</small></div><div><strong>{workout.planned_duration_minutes ?? "—"} min</strong><small>{workout.planned_distance_km ? `${workout.planned_distance_km} km` : "Distance open"}</small></div><span className={`status ${workout.status}`}>{workout.status}</span></article>; }
function Empty({text}:{text:string}) { return <div className="empty">{text}</div>; }

function PlansPage() { const [plans,setPlans]=useState<TrainingPlan[]>([]); useEffect(()=>{api.plans().then(x=>setPlans(x.results));},[]); return <><div className="section-title"><div><span className="eyebrow">TRAINING</span><h2>Plans and sessions</h2></div></div>{plans.map(p=><section className="plan" key={p.id}><div className="plan-head"><div><h3>{p.title}</h3><p>{p.start_date} — {p.end_date}</p></div><span className="status active">{p.is_active?"active":"archived"}</span></div>{p.weeks.map(w=><div key={w.id}><h4>Week {w.week_number} · {w.start_date}</h4>{w.workouts.map(x=><WorkoutRow key={x.id} workout={x}/>)}</div>)}</section>)}{!plans.length&&<Empty text="No training plans available."/>}</>; }

function AthletesPage() { const {user}=useAuth(); const [athletes,setAthletes]=useState<Relationship[]>([]); const [email,setEmail]=useState(""); const [message,setMessage]=useState(""); useEffect(()=>{if(user?.role==="coach")api.athletes().then(x=>setAthletes(x.results));},[user]); if(user?.role!=="coach")return <Navigate to="/"/>; async function invite(e:FormEvent){e.preventDefault();try{await api.invite(email);setMessage("Invitation sent.");setEmail("");}catch(err){setMessage((err as Error).message)}} return <><div className="section-title"><div><span className="eyebrow">ROSTER</span><h2>Your athletes</h2></div><form className="invite" onSubmit={invite}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="athlete@example.com" required/><button className="primary">Invite athlete</button></form></div>{message&&<div className="notice">{message}</div>}<section className="athlete-grid">{athletes.map(r=><article className="athlete" key={r.id}><span>{r.athlete.first_name?.[0]||r.athlete.username[0]}</span><h3>{r.athlete.first_name ? `${r.athlete.first_name} ${r.athlete.last_name}` : r.athlete.username}</h3><p>{r.athlete.profile?.sport||"Sport not selected"}</p><small>{r.is_active?"Active coaching":"Inactive"}</small></article>)}</section>{!athletes.length&&<Empty text="Invite your first athlete to begin planning."/>}</>; }

export default function App(){return <Routes><Route path="/auth" element={<AuthPage/>}/><Route path="/verify-email" element={<VerifyEmailPage/>}/><Route path="/account-help" element={<AccountHelpPage/>}/><Route path="/reset-password" element={<ResetPasswordPage/>}/><Route path="/invitations/:token" element={<InvitationPage/>}/><Route path="/" element={<Protected><Overview/></Protected>}/><Route path="/plans" element={<Protected><PlansPage/></Protected>}/><Route path="/athletes" element={<Protected><AthletesPage/></Protected>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
