export type Role = "coach" | "athlete";
export interface CoachSummary { id: number; username: string; first_name: string; last_name: string }
export interface User { id: number; username: string; email: string; first_name: string; last_name: string; role: Role; profile: { sport: string; bio: string; date_of_birth: string | null }; coach?: CoachSummary | null }
export interface Page<T> { count: number; next: string | null; previous: string | null; results: T[] }
export interface Exercise { id: number; workout: number; name: string; step_type: string; order: number; description: string; repetitions: number | null; duration_seconds: number | null; distance_meters: number | null; recovery_seconds: number | null; target_type: string; target_min: string | null; target_max: string | null; target_unit: string; resolved_target_min: string | null; resolved_target_max: string | null; resolved_target_unit: string; resolved_target_label: string }
export interface CoachComment { id: number; workout: number; coach: number; coach_name: string; body: string; created_at: string }
export interface Workout { id: number; weekly_plan: number; title: string; sport: string; workout_type: string; status: string; scheduled_at: string; planned_duration_minutes: number | null; planned_distance_km: string | null; intensity: string; notes: string; exercises: Exercise[]; coach_comments: CoachComment[]; log?: WorkoutLog | null }
export interface WorkoutLog { id: number; workout: number; completed_at: string; actual_duration_minutes: number | null; actual_distance_km: string | null; perceived_exertion: number | null; notes: string }
export interface WeeklyPlan { id: number; training_plan: number; week_number: number; start_date: string; notes: string; workouts: Workout[] }
export interface TrainingPlan { id: number; coach: number; title: string; description: string; primary_sport: string; athlete: number; start_date: string; end_date: string; is_active: boolean; weeks: WeeklyPlan[] }
export interface Relationship { id: number; coach: User; athlete: User; is_active: boolean }
export interface Analytics { total_workouts: number; completed_workouts: number; skipped_workouts: number; completion_rate: number; planned_duration_minutes: string; actual_duration_minutes: string; planned_distance_km: string; actual_distance_km: string; average_perceived_exertion: number | null }
export interface TrainingZone { id: number; athlete: number; sport: string; metric: string; zone_number: number; name: string; lower_bound: string; upper_bound: string; unit: string; display_range: string }
export interface AthleteThreshold { id: number; athlete: number; sport: string; threshold_heart_rate: number | null; maximum_heart_rate: number | null; functional_threshold_power: number | null; threshold_pace_seconds_per_km: number | null; critical_swim_speed_seconds_per_100m: number | null; heart_rate_basis: string; zones: TrainingZone[]; updated_at: string }
